# Generated by Django 3.0.2 on 2020-01-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHT11Data',
            fields=[
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('time', models.TimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
