# Generated by Django 3.0.2 on 2020-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11data',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
