# Generated by Django 3.0.2 on 2020-01-27 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end_app', '0002_auto_20200123_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11data',
            name='humidity',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='dht11data',
            name='temperature',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
