# Generated by Django 3.2 on 2021-04-28 19:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end_app', '0002_auto_20200207_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDHT11Data',
            fields=[
                ('record_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(2147483647), django.core.validators.MinValueValidator(0)])),
                ('temperature', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)])),
                ('humidity', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)])),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'new_dht11_data',
            },
        ),
    ]
