# Generated by Django 3.0.3 on 2020-02-07 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end_app', '0003_auto_20200127_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False),
        ),
    ]
